#!/bin/sh

set -e

#
# Set up the test database
#
bundle exec rake db:test:prepare

#
# Rspec
#
bundle exec rspec --format documentation spec

#
# Konacha
#
bundle exec rake konacha:run

#
# Engines
#
cd engines/blog_app
bundle install
bundle exec rake db:setup RAILS_ENV=test
bundle exec rspec spec

cd engines/training_app
bundle install
bundle exec rake db:setup RAILS_ENV=test
bundle exec rspec spec

